laravel/routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Auth::routes();

Route::middleware(['auth'])->group(function (){
    Route::resource('project', 'ProjectsController');
    Route::resource('user', 'UsersController')->only([
        'index', 'update', 'userImage'
    ]);

    Route::delete('project/fileDestroy/{id}', 'ProjectsController@fileDestroy');

    Route::get('csvCreate', 'ProjectsController@csvCreate')->name('project.csvCreate');
    Route::post('csvCreate', 'ProjectsController@csvCreateStore')->name('project.csvCreate.store');
    Route::get('projectToPDF/{id}', 'ProjectsController@projectToPDF')->name('project.projectToPDF');
    Route::get('allProjectsToCSV', 'ProjectsController@allProjectsToCSV')->name('project.allProjectsToCSV');

    Route::post('userImage', 'UsersController@userImage')->name('user.image');
});

laravel/resources/views/projectsPages/create.blade.php
@extends('layouts.app')

@section('content')
    <div class="row col-12">
        <form id="form"
              class="col-lg-5 mx-auto"
              action="{{ route('project.store') }}"
              enctype="multipart/form-data"
              method="POST">
            @csrf
            @method('POST')


            @if (isset($errors) ? $errors->any() : false)
                <div class="col-12">
                    <div class="alert alert-danger">
                        <ul>
                            @foreach ($errors->all() as $error)
                                <li>{{ $error }}</li>
                            @endforeach
                        </ul>
                    </div>
                </div>
            @endif
            @if (\Session::has('message'))
                <div class="col-12">
                    <div class="alert alert-success">
                        <ul>
                            <li>{{ \Session::get('message')}}</li>
                        </ul>
                    </div>
                </div>
            @endif
            <div class="form-group row">
                <label for="title" class="col-sm-3 col-form-label">Title:</label>
                <div class="col-sm-9">
                    <input type="text"
                           id="title"
                           name="title"
                           class="form-control"
                           placeholder="Enter title..."
                           required>
                </div>
            </div>
            <div class="form-group row">
                <label for="description" class="col-sm-3 col-form-label">Description:</label>
                <div class="col-sm-9">
                    <textarea type="text"
                              id="description"
                              maxlength="2000"
                              name="description"
                              class="form-control"
                              placeholder="Enter description..."
                              style="resize: none"
                              required></textarea>
                </div>
            </div>
            <div class="form-group row">
                <label for="organization" class="col-sm-3 col-form-label">Organization:</label>
                <div class="col-sm-9">
                    <input type="text"
                           id="organization"
                           name="organization"
                           class="form-control"
                           placeholder="Enter organization...">
                </div>
            </div>
            <div class="form-group row">
                <label for="start" class="col-sm-3 col-form-label">Start time:</label>
                <div class="col-sm-9">
                    <input type="date"
                           id="start"
                           name="start"
                           class="form-control"
                           placeholder="Enter start time...">
                </div>
            </div>
            <div class="form-group row">
                <label for="end" class="col-sm-3 col-form-label">End time:</label>
                <div class="col-sm-9">
                    <input type="date"
                           id="end"
                           name="end"
                           class="form-control"
                           placeholder="Enter end time...">
                </div>
            </div>
            <div class="form-group row">
                <label for="role" class="col-sm-3 col-form-label">Role:</label>
                <div class="col-sm-9">
                    <input type="text"
                           id="role"
                           name="role"
                           class="form-control"
                           placeholder="Enter role..."
                           required>
                </div>
            </div>
            <div class="form-group row">
                <label for="link" class="col-sm-3 col-form-label">Link:</label>
                <div class="col-sm-9">
                    <input type="text"
                           id="link"
                           name="link"
                           class="form-control"
                           placeholder="Enter link...">
                </div>
            </div>
            <div class="form-group row">
                <label for="skills" class="col-sm-3 col-form-label">Skills:</label>
                <div class="col-sm-9">
                    <input type="text"
                           id="skills"
                           name="skills"
                           class="form-control"
                           placeholder="Enter skills like: planing, time managment, ...">
                </div>
            </div>
            <div class="form-group row">
                <label for="type" class="col-sm-3 col-form-label">Type:</label>
                <div class="col-sm-9">
                    <select id="type" name="type" class="form-control" required>
                        <option value="" disabled selected>Choose your option</option>
                        @foreach($types as $type)
                            <option value="{{ strtolower($type) }}">{{ $type }}</option>
                        @endforeach
                    </select>
                </div>
            </div>
            <div class="form-group row">
                <label for="attachments" class="col-sm-3 col-form-label">Attachments:</label>
                <div class="col-sm-9">
                    <input type="file"
                           id="attachments"
                           name="attachments[]"
                           class="form-control-file"
                           accept=".jpg, .png, .doc, .docx, .pdf"
                           multiple>
                </div>
            </div>
            <div class="form-group row">
                <a class="btn btn-primary btn-lg"
                   id="createProject"
                   href="#">Create</a>
            </div>
        </form>
    </div>


    <script>
        $(document).ready(() => {
            $('#createProject').on('click', (e) => {
                e.preventDefault();

                const requiredInputs = [
                    $('#title'),
                    $('#description'),
                    $('#role'),
                    $('#type')
                ];

                const errors = [];
                let success = true;

                requiredInputs.forEach(function (item) {
                    item.val() === '' ? success = false : '';
                    item.val() === '' ? errors.push(item.attr('id')) : '';
                });

                if (success) {
                    let formData = new FormData(document.getElementById('form'));
                    $.ajax({
                        type: 'POST',
                        headers: {
                            'X-CSRF-Token': '{{ csrf_token() }}',
                        },
                        url: '{{url("project")}}',
                        data: formData,
                        dataType: 'json',
                        processData: false,
                        contentType: false,
                        success: function (response) {
                            window.location.replace('{{url("project")}}');                        },
                        error: function () {
                            console.log('fail');
                        }
                    });
                } else {
                    errors.forEach(function (item) {
                        $(`#${item}`).addClass('alert alert-danger')
                    });
                }
            })
        });
    </script>
@endsection

laravel/resources/views/projectsPages/csvCreate.blade.php
@extends('layouts.app')

@section('content')
    <div class="row col-12">
        <form id="form"
              class="col-lg-5 mx-auto"
              action="{{ route('project.store') }}"
              enctype="multipart/form-data"
              method="POST">
            @csrf
            @method('POST')


            @if (isset($errors) ? $errors->any() : false)
                <div class="col-12">
                    <div class="alert alert-danger">
                        <ul>
                            @foreach ($errors->all() as $error)
                                <li>{{ $error }}</li>
                            @endforeach
                        </ul>
                    </div>
                </div>
            @endif
            @if (\Session::has('message'))
                <div class="col-12">
                    <div class="alert alert-success">
                        <ul>
                            <li>{{ \Session::get('message')}}</li>
                        </ul>
                    </div>
                </div>
            @endif
            <label for="csv" class="col-sm-5 col-form-label">Add CSV/EXCEL file:</label>
            <div class="form-group row">
                <div class="col-sm-9">
                    <input type="file"
                           id="csv"
                           name="csv"
                           class="form-control-file"
                           accept=".csv"
                           multiple>
                </div>
            </div>
            <div class="form-group row">
                <a class="btn btn-primary btn-lg"
                   id="createProject"
                   href="#">Create</a>
            </div>
        </form>
    </div>


    <script>
        $(document).ready(() => {
            $('#createProject').on('click', (e) => {
                e.preventDefault();

                const requiredInputs = [
                    $('#csv'),
                ];

                const errors = [];
                let success = true;

                requiredInputs.forEach(function (item) {
                    item.val() === '' ? success = false : '';
                    item.val() === '' ? errors.push(item.attr('id')) : '';
                });

                if (success) {
                    let formData = new FormData(document.getElementById('form'));
                    $.ajax({
                        type: 'POST',
                        headers: {
                            'X-CSRF-Token': '{{ csrf_token() }}',
                        },
                        url: '{{url("csvCreate")}}',
                        data: formData,
                        dataType: 'json',
                        processData: false,
                        contentType: false,
                        success: function (response) {
                            window.location.replace('{{url("project")}}');
                            // console.log(response);
                        },
                        error: function (response) {
                            console.log(response);
                        }
                    });
                } else {
                    errors.forEach(function (item) {
                        $(`#${item}`).addClass('alert alert-danger')
                    });
                }
            })
        });
    </script>
@endsection

laravel/resources/views/projectsPages/index.blade.php
@extends('layouts.app')

@section('content')
    <div class="row">
        <div class="col-12">
            <table id="dtMaterialDesignExample" class="table table-striped" cellspacing="0" width="100%">
                <thead>
                <tr>
                    <th class="th-sm">#</th>
                    <th class="th-sm">Title</th>
                    <th class="th-sm">Description</th>
                    <th class="th-sm">Organization</th>
                    <th class="th-sm">Start</th>
                    <th class="th-sm">End</th>
                    <th class="th-sm">Role</th>
                    <th class="th-sm">Link</th>
                    <th class="th-sm">Type</th>
                    <th class="th-sm">Created_at</th>
                    <th class="th-sm">Updated_at</th>
                    <th class="th-sm"></th>
                </tr>
                </thead>
                <tbody>
                @if ($projects->total() === 0)
                    <tr>
                        <td colspan="3" class="text-center">Empty...</td>
                    </tr>
                @else
                    @foreach($projects->items() as $item)
                        <tr>
                            <th>{{ $item->id }}</th>
                            <th>
                                <a href="{{ route('project.show', $item->id) }}">{{ $item->name }}</a>
                            </th>
                            <th>
                                <div class="dropdown show">
                                    <a class="dropdown-toggle" href="#" role="button"
                                       id="dropdownMenuLink" data-toggle="dropdown" aria-haspopup="true"
                                       aria-expanded="false">Description</a>

                                    <div class="dropdown-menu" aria-labelledby="dropdownMenuLink" style="width: 500px;">
                                        {{ $item->description }}
                                    </div>
                                </div>
                            </th>
                            <th>{{ $item->organization }}</th>
                            <th>{{ $item->start }}</th>
                            <th>{{ $item->end }}</th>
                            <th>{{ $item->role }}</th>
                            <th>
                                <a href="{{ $item->link }}" target="_blank">{{ $item->link }}</a>
                            </th>
                            <th>{{ $item->type }}</th>
                            <th>{{ $item->created_at }}</th>
                            <th>{{ $item->updated_at }}</th>
                            <td class="text-right">
                                <div class="btn-group text-left">
                                    <a href="{{ route('project.edit', $item->id) }}"
                                       class="btn btn-primary btn-sm" data-toggle="tooltip"
                                       data-placement="top" title="Редактировать"><i class="fas fa-edit"></i></a>

                                    @if(auth()->user()->isAdmin())
                                        <a href="#" class="btn btn-sm btn-danger" data-toggle="modal"
                                           data-target="#questionModal-{{ $item->id }}"><i class="fas fa-trash"></i></a>

                                        <div class="modal fade" id="questionModal-{{ $item->id }}" tabindex="-1"
                                             role="dialog" aria-hidden="true">
                                            <div class="modal-dialog modal-xl" role="document">
                                                <div class="modal-content">
                                                    <div class="modal-header">
                                                        <h5 class="modal-title">Вы уверены что хотите удалить?</h5>
                                                        <button type="button" class="close" data-dismiss="modal"
                                                                aria-label="Close">
                                                            <span aria-hidden="true">×</span>
                                                        </button>
                                                    </div>
                                                    <div class="modal-body text-right">
                                                        <a class="btn btn-sm btn-danger deleteButton"
                                                           data-dismiss="modal"
                                                           data-id="{{$item->id}}"
                                                           href="#"><i class="fas fa-trash"></i></a>
                                                    </div>
                                                </div>
                                            </div>
                                        </div>
                                    @endif
                                </div>
                            </td>
                        </tr>
                    @endforeach
                @endif
                </tbody>
            </table>
        </div>
        <div class="col-12">
            {{$projects->links()}}
        </div>
    </div>

    <script>
        $(document).ready(() => {
            $.noConflict();
            $('#dtMaterialDesignExample').DataTable( {
                scrollX:        true,
                scrollCollapse: true,
                paging:         false,
            } );
            $('.deleteButton').on('click', (e) => {
                const projectId = $(e.currentTarget).data('id');
                $.ajax({
                    type: 'delete',
                    url: '{{url("project/")}}' + '/' + projectId,
                    headers: {
                        'X-CSRF-Token': '{{ csrf_token() }}',
                    },
                    data: {},
                    success: function (response) {
                        $('#' + projectId).remove();
                        console.log(response);
                    },
                    error: function (response) {
                        console.log(response);
                    }
                });
            });
        });
    </script>
@endsection

laravel/resources/views/projectsPages/show.blade.php
@extends('layouts.app')

@section('content')
    <div class="row">
        <div class="col-12">
            <table id="dtMaterialDesignExample" class="table table-striped" cellspacing="0" width="100%">
                <thead>
                <tr>
                    <th>#</th>
                    <th>Title</th>
                    <th>Description</th>
                    <th>Organization</th>
                    <th>Start</th>
                    <th>End</th>
                    <th>Role</th>
                    <th>Link</th>
                    <th>Type</th>
                    <th>Skills</th>
                    <th>Files</th>
                    <th>Created_at</th>
                    <th>Updated_at</th>
                    <th></th>
                </tr>
                </thead>
                <tbody>
                <tr>
                    <th>{{ $project->id }}</th>
                    <th>{{ $project->name }}</th>
                    <th>
                        <a href="#" data-toggle="modal"
                           data-target="#description">Description</a>

                        <div class="modal fade" id="description" tabindex="-1"
                             role="dialog" aria-hidden="true">
                            <div class="modal-dialog modal-xl" role="document">
                                <div class="modal-content">
                                    <div class="modal-header">
                                        <h5 class="modal-title">Description</h5>
                                        <button type="button" class="close" data-dismiss="modal"
                                                aria-label="Close">
                                            <span aria-hidden="true">×</span>
                                        </button>
                                    </div>
                                    <div class="modal-body text-right">
                                        {{ $project->description }}
                                    </div>
                                </div>
                            </div>
                        </div>
                    </th>
                    <th>{{ $project->organization }}</th>
                    <th>{{ $project->start }}</th>
                    <th>{{ $project->end }}</th>
                    <th>{{ $project->role }}</th>
                    <th>
                        <a href="{{ $project->link }}" target="_blank">{{ $project->link }}</a>
                    </th>
                    <th>{{ $project->type }}</th>
                    <th>
                        <a href="#" data-toggle="modal"
                           data-target="#skills">Skills</a>

                        <div class="modal fade" id="skills" tabindex="-1"
                             role="dialog" aria-hidden="true">
                            <div class="modal-dialog modal-xl" role="document">
                                <div class="modal-content">
                                    <div class="modal-header">
                                        <h5 class="modal-title">Skills</h5>
                                        <button type="button" class="close" data-dismiss="modal"
                                                aria-label="Close">
                                            <span aria-hidden="true">×</span>
                                        </button>
                                    </div>
                                    <div class="modal-body text-right">
                                        <ul>
                                            @foreach($project->skills as $skill)
                                                <li>{{ $skill->name }}</li>
                                            @endforeach
                                        </ul>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </th>
                    <th>
                        <a href="#" data-toggle="modal"
                           data-target="#files">Files</a>

                        <div class="modal fade" id="files" tabindex="-1"
                             role="dialog" aria-hidden="true">
                            <div class="modal-dialog modal-xl" role="document">
                                <div class="modal-content">
                                    <div class="modal-header">
                                        <h5 class="modal-title">Files</h5>
                                        <button type="button" class="close" data-dismiss="modal"
                                                aria-label="Close">
                                            <span aria-hidden="true">×</span>
                                        </button>
                                    </div>
                                    <div class="modal-body text-right">
                                        <ul>
                                            @foreach($project->files as $file)
                                                <li>{{ $file->name }}</li>
                                            @endforeach
                                        </ul>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </th>
                    <th>{{ $project->created_at }}</th>
                    <th>{{ $project->updated_at }}</th>
                    <td class="text-right">
                        <div class="btn-group text-left">
                            <a href="{{ route('project.projectToPDF', $project->id) }}"
                               class="btn btn-success btn-sm"
                               id="downloadPDF"
                               data-toggle="tooltip"
                               data-placement="top"
                               title="Download as PDF"><i class="fas fa-download"></i></a>
                            <a href="{{ route('project.edit', $project->id) }}"
                               class="btn btn-primary btn-sm" data-toggle="tooltip"
                               data-placement="top" title="Edit"><i class="fas fa-edit"></i></a>

                            @if(auth()->user()->isAdmin())
                                <a href="#" class="btn btn-sm btn-danger" data-toggle="modal"
                                   data-target="#questionModal-{{ $project->id }}" title="Remove"><i class="fas fa-trash"></i></a>

                                <div class="modal fade" id="questionModal-{{ $project->id }}" tabindex="-1"
                                     role="dialog" aria-hidden="true">
                                    <div class="modal-dialog modal-xl" role="document">
                                        <div class="modal-content">
                                            <div class="modal-header">
                                                <h5 class="modal-title">Вы уверены что хотите удалить?</h5>
                                                <button type="button" class="close" data-dismiss="modal"
                                                        aria-label="Close">
                                                    <span aria-hidden="true">×</span>
                                                </button>
                                            </div>
                                            <div class="modal-body text-right">
                                                <a class="btn btn-sm btn-danger deleteButton"
                                                   data-dismiss="modal"
                                                   data-id="{{$project->id}}"><i class="fas fa-trash"></i></a>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            @endif
                        </div>
                    </td>
                </tr>
                </tbody>
            </table>
        </div>
    </div>

    <script>
        $(document).ready(() => {
            $.noConflict();
            $('#dtMaterialDesignExample').DataTable({
                scrollX:        true,
                scrollCollapse: true,
                paging:         false,
            });
            $('.deleteButton').on('click', (e) => {
                const projectId = $(e.currentTarget).data('id');
                $.ajax({
                    type: 'delete',
                    url: '{{url("project/")}}' + '/' + projectId,
                    headers: {
                        'X-CSRF-Token': '{{ csrf_token() }}',
                    },
                    data: {},
                    success: function (response) {
                        window.location.replace('{{url("project/")}}');
                    },
                    error: function (response) {
                        console.log(response);
                    }
                });
            });
        });
    </script>
@endsection